### ISSUE TITLE
Cubith Game Pic

### ISSUE THREAD

**Issue by caeltarifa** [MikiMirai/MikiMirai#1]
Coudl you please include a pic or video to inspect the expected result versus how it is working?

**Comment by MikiMirai** [comment]
Yeah, sorry for taking this long to reply, I'll add an image soon.

**Comment by caeltarifa** [comment]
Sounds good.

I can add it if you approve my merge request for Readme file.

Thanks for writing back.

Cael

**Comment by MikiMirai** [comment]
Okay that sounds nice, I might start working on the random levels soon and I'm planning to have a slow motion power with the back button.

**Comment by MikiMirai** [comment]
@caeltarifa I added the screenshots and 2 things to the TODO list, closing the issue.
Screenshots will be updated as I (hopefully get to) add more things to the game.
Thank you for submitting your request here <3
